# Generated by Django 3.0.3 on 2020-11-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esp', '0002_delete_labuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=10, unique=True)),
                ('typeOfSensor', models.CharField(choices=[('Temperature Sensor', 'Temperature Sensor'), ('CO2 gas Sensor', 'CO2 gas Sensor'), ('Humidity Sensor', 'Humidity Sensor'), ('Motion Sensor', 'Motion Sensor'), ('Pressure Sensor', 'Pressure Sensor')], default='Temperature Sensor', max_length=20, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('min_threshold', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_threshold', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
