# Generated by Django 3.1a1 on 2020-12-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_sensorreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorValue', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sensorId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='esp.sensorreg')),
            ],
        ),
    ]
